version: '3.7'
services:
  php:
    build: 
      context: ./docker/app
    extra_hosts:
      - "host.docekr.internal:host-gateway"
    ports:
      - 8183:8183
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: "php -S 0.0.0.0:8183"